baseURL = "https://sjsu-dev2.github.io/libembeddedhal/"
languageCode = "en-us"
title = "libembeddedhal docs"
theme = "hugo-theme-relearn"

[params]
  themeVariant = "green"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i><img height='150' src='https://upload.wikimedia.org/wikipedia/commons/b/b5/Conan_package_manager_logo.png' style='height: 1em'></i>  Search conan"
url = ""
weight = 10

[[menu.shortcuts]]
name = "<i><img height='150' src='https://vcpkg.io/assets/mark/mark.svg' style='height: 1em'></i> Search vcpkg"
url = ""
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/SJSU-Dev2/libembeddedhal"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "/showcase/"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits/"
weight = 50
