name: ğŸ—ï¸ Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      app_folder:
        type: string
        required: true

jobs:
  find_directory:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - id: check_directory
        continue-on-error: true
        run: ls ${{ inputs.app_folder }}
    outputs:
      found: ${{ steps.check_directory.outcome }}

  build:
    needs: find_directory
    if: needs.find_directory.outputs.found == 'success'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-12
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    environment: Production
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Install CMake + Conan + GCovr
        run: pip3 install --upgrade cmake conan==1.57.0 gcovr

      - name: ğŸ“¡ Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan --insert

      - name: ğŸ“¡ Enable conan revision mode
        run: conan config set general.revisions_enabled=True

      - name: ğŸ“¡ Create and setup default profile
        run: |
            conan profile new default --detect
            conan profile update settings.build_type=Debug default
            conan profile update settings.compiler.libcxx=libstdc++ default
            conan profile update settings.compiler=gcc default
            conan profile update settings.compiler.version=11 default

      - name: ğŸ‘ï¸â€ğŸ—¨ï¸ Show conan profile
        run: conan profile show default

      - name: ğŸ“¦ Generate Package & Install Library (if possible)
        continue-on-error: true
        run: conan create .

      - name: ğŸ“‚ Create build directory
        working-directory: ${{ inputs.app_folder }}
        run: mkdir -p build

      - name: ğŸ“ Generate conan dependency files
        working-directory: ${{ inputs.app_folder }}/build
        run: conan install ..

      - name: ğŸ—ï¸ Activate build environment
        working-directory: ${{ inputs.app_folder }}/build
        if: matrix.os != 'windows-2022'
        run: source conanbuild.sh

      - name: ğŸ—ï¸ Activate build environment
        working-directory: ${{ inputs.app_folder }}/build
        if: matrix.os == 'windows-2022'
        run: ./conanbuild.bat

      - name: ğŸ—ï¸ Generate Build Files
        working-directory: ${{ inputs.app_folder }}/build
        run: cmake ..  -G "Unix Makefiles"

      - name: ğŸ—ï¸ Build Application
        working-directory: ${{ inputs.app_folder }}/build
        run: cmake --build . --config Release
