name: ğŸ—ï¸ Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      app_folder:
        type: string
        required: true

jobs:
  find_directory:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - id: check_directory
        continue-on-error: true
        run: ls ${{ inputs.app_folder }}
    outputs:
      found: ${{ steps.check_directory.outcome }}

  build:
    needs: find_directory
    if: needs.find_directory.outputs.found == 'success'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-12
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Install CMake + Conan
        run: pip3 install --upgrade cmake conan

      - name: ğŸ“¡ Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: ğŸ“¡ Create and setup default profile
        run: conan profile detect --force

      - name: ğŸ‘ï¸â€ğŸ—¨ï¸ Show conan profile
        run: conan profile show

      - name: ğŸ“¦ Generate Package & Install Library (if possible)
        continue-on-error: true
        run: conan create . --build=missing -s compiler.version=11 -s compiler.cppstd=20 -s compiler=gcc -s compiler.libcxx=libstdc++ -s:b compiler.cppstd=20 -s:b compiler=gcc -s:b compiler.version=11 -s:b compiler.libcxx=libstdc++ -c tools.build:skip_test=True

      - name: ğŸ—ï¸ Build
        working-directory: ${{ inputs.app_folder }}
        run: conan build . --build=missing -s:h compiler.version=11 -s:h compiler.cppstd=20 -s:h compiler=gcc -s:h compiler.libcxx=libstdc++
