name: 游 deploy

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: 游닌 Install g++-11
        run: sudo apt install g++-11 build-essential

      - name: 游닌 Install CMake & Conan
        run: pip install cmake conan

      - name: 游니 Add `libhal-trunk` conan remote
        run: |
             conan remote add libhal-trunk \
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan --insert

      - name: 游니 Enable conan revision mode
        run: conan config set general.revisions_enabled=True

      - name: 游닍 Create Conan Package & Verify Test Package
        run: conan create . --test-folder test_package

      - name: 游니 Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan user -p $API_KEY -r libhal-trunk $JFROG_USER

      - name: 游 Upload package to `libhal-trunk` repo
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
             conan upload "${{ inputs.library }}/*" --confirm --all \
             -r=libhal-trunk
