name: ğŸ§ª tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: gcc
            compiler_version: 11
            compiler: g++-11
            os: ubuntu-22.04
            standard_library: libstdc++
            install_name: g++-11

          - toolchain: clang
            compiler_version: 14
            compiler: clang++
            os: ubuntu-22.04
            standard_library: libc++
            install_name: clang-14

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Update APT
        run: sudo apt update

      - name: ğŸ“¥ Install ${{ matrix.install_name }}
        run: sudo apt install ${{ matrix.install_name }} build-essential

      - name: ğŸ“¥ Install CMake + Conan + GCovr
        run: pip3 install --upgrade cmake conan gcovr

      - name: ğŸ“¡ Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan --insert

      - name: ğŸ“¡ Enable conan revision mode
        run: conan config set general.revisions_enabled=True

      - name: ğŸ“¡ Create and setup default profile
        run: |
            conan profile new default --detect
            conan profile update settings.build_type=Debug default
            conan profile update \
              settings.compiler.libcxx=${{ matrix.standard_library }} default
            conan profile update \
              settings.compiler=${{ matrix.toolchain }} default
            conan profile update \
              settings.compiler.version=${{ matrix.compiler_version }} default

      - name: ğŸ“¦ Build and Install Package
        run: conan create . -r=libhal-trunk --update -pr:b=default
                -e CXX=${{ matrix.compiler }}

      - name: ğŸ“‚ Create build directory
        working-directory: tests
        run: mkdir -p build

      - name: ğŸ“¥ Install conan dependencies
        working-directory: tests/build
        run: conan install .. -r=libhal-trunk --update
                -e CXX=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run CMake
        working-directory: tests/build
        run: cmake .. -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run Make
        working-directory: tests/build
        run: make -j unit_test

      - name: ğŸ”¬ Build & Run Unit Tests
        working-directory: tests/build
        run: ./unit_test

  mac:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: clang
            compiler_version: 14
            compiler: clang++
            os: macos-12
            standard_library: libc++
            install_name:

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Install ${{ matrix.install_name }}
        if: ${{ matrix.install_name }}
        run: brew install ${{ matrix.install_name }}

      - name: ğŸ“¥ Install CMake + Conan + GCovr
        run: pip3 install --upgrade cmake conan gcovr

      - name: ğŸ“¡ Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan --insert

      - name: ğŸ“¡ Enable conan revision mode
        run: conan config set general.revisions_enabled=True

      - name: ğŸ“¡ Create and setup default profile
        run: |
            conan profile new default --detect
            conan profile update settings.build_type=Debug default
            conan profile update \
              settings.compiler.libcxx=${{ matrix.standard_library }} default
            conan profile update \
              settings.compiler=${{ matrix.toolchain }} default
            conan profile update \
              settings.compiler.version=${{ matrix.compiler_version }} default

      - name: ğŸ“¦ Build and Install Package
        run: conan create . -r=libhal-trunk --update -pr:b=default
                -e CXX=${{ matrix.compiler }}

      - name: ğŸ“‚ Create build directory
        working-directory: tests
        run: mkdir -p build

      - name: ğŸ“¥ Install conan dependencies
        working-directory: tests/build
        run: conan install .. -r=libhal-trunk --update
                -e CXX=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run CMake
        working-directory: tests/build
        run: cmake .. -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run Make
        working-directory: tests/build
        run: make -j unit_test

      - name: ğŸ”¬ Build & Run Unit Tests
        working-directory: tests/build
        run: ./unit_test
