name: ğŸ§ª tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
      coverage:
        required: true
        type: boolean
      fail_on_coverage:
        required: true
        type: boolean
      coverage_threshold:
        required: true
        type: string

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: gcc
            compiler_version: 11
            compiler: g++-11
            os: ubuntu-22.04
            standard_library: libstdc++
            install_name: build-essential g++-11
            enable_coverage: ${{ inputs.coverage }}
            enable_latest_version_badge: true

          # - toolchain: clang
          #   compiler_version: 14
          #   compiler: clang++
          #   os: ubuntu-22.04
          #   standard_library: libc++
          #   install_name: build-essential clang-14 llvm-14-dev libc++-dev libc++abi-dev --install-suggests
          #   enable_coverage: false
          #   enable_latest_version_badge: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Update APT
        run: sudo apt update

      - name: ğŸ“¥ Install ${{ matrix.install_name }}
        run: sudo apt install ${{ matrix.install_name }}

      - name: ğŸ“¥ Install CMake + Conan + GCovr
        run: pip3 install --upgrade cmake conan gcovr

      - name: ğŸ“¡ Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan --insert

      - name: ğŸ“¡ Enable conan revision mode
        run: conan config set general.revisions_enabled=True

      - name: ğŸ“¡ Create and setup default profile
        run: |
            conan profile new default --detect
            conan profile update settings.build_type=Debug default
            conan profile update \
              settings.compiler.libcxx=${{ matrix.standard_library }} default
            conan profile update \
              settings.compiler=${{ matrix.toolchain }} default
            conan profile update \
              settings.compiler.version=${{ matrix.compiler_version }} default

      - name: ğŸ“¦ Generate Package & Install Library
        run: conan create . --test-folder test_package

      - name: ğŸ“‚ Create build directory
        working-directory: tests
        run: mkdir -p build

      - name: ğŸ“¥ Install conan dependencies
        working-directory: tests/build
        run: conan install .. -r=libhal-trunk --update
                -e CXX=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run CMake
        working-directory: tests/build
        run: cmake .. -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run Make
        working-directory: tests/build
        run: make -j unit_test

      - name: ğŸ”¬ Build & Run Unit Tests
        working-directory: tests/build
        run: ./unit_test

      - name: ğŸ” Generate Code Coverage
        if: ${{ matrix.enable_coverage }}
        working-directory: tests/build
        run: mkdir coverage/ && python3 -m gcovr
             --root ../../
             --exclude ".*/third_party/.*"
             --cobertura coverage/coverage.xml
             --html coverage/index.html --html-details
             --sort-percentage

      - name: Coverage Summary
        if: ${{ matrix.enable_coverage }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: tests/build/coverage/coverage.xml
          badge: true
          fail_below_min: ${{ inputs.fail_on_coverage }}
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: ${{ inputs.coverage_threshold }}

      - name: Extract & Save Coverage SVG
        if: ${{ matrix.enable_coverage }}
        run: wget
             $(cat code-coverage-results.md |
               grep -Eo 'https://img.shields.io/badge/[^)]*')
              -O tests/build/coverage/coverage.svg

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.enable_coverage }}
        with:
          name: coverage
          retention-days: 1
          path: tests/build/coverage/

  mac:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: clang
            compiler_version: 14
            compiler: clang++
            os: macos-12
            standard_library: libc++
            install_name:

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: ğŸ“¥ Install ${{ matrix.install_name }}
        if: ${{ matrix.install_name }}
        run: brew install ${{ matrix.install_name }}

      - name: ğŸ“¥ Install CMake + Conan + GCovr
        run: pip3 install --upgrade cmake conan gcovr

      - name: ğŸ“¡ Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan --insert

      - name: ğŸ“¡ Enable conan revision mode
        run: conan config set general.revisions_enabled=True

      - name: ğŸ“¡ Create and setup default profile
        run: |
            conan profile new default --detect
            conan profile update settings.build_type=Debug default
            conan profile update \
              settings.compiler.libcxx=${{ matrix.standard_library }} default
            conan profile update \
              settings.compiler=${{ matrix.toolchain }} default
            conan profile update \
              settings.compiler.version=${{ matrix.compiler_version }} default

      - name: ğŸ“‚ Create build directory
        working-directory: tests
        run: mkdir -p build

      - name: ğŸ“¥ Install conan dependencies
        working-directory: tests/build
        run: conan install .. -r=libhal-trunk --update
                -e CXX=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run CMake
        working-directory: tests/build
        run: cmake .. -D CMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: ğŸ—ï¸ Run Make
        working-directory: tests/build
        run: make -j unit_test

      - name: ğŸ”¬ Build & Run Unit Tests
        working-directory: tests/build
        run: ./unit_test
